CREATE TABLE IF NOT EXISTS books (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    title VARCHAR(150) NOT NULL,
    author VARCHAR(100) NOT NULL,
    publisher VARCHAR(100),
    cover LONGBLOB,
    status VARCHAR(50)
);